### ISSUE TITLE
How to accurately track the phone's orientation 

### ISSUE THREAD

**Issue by MasterHansCoding** [TheDeveloperGuy/ivry_custom_tracking#1]
Hello,

Do you know how to accurately track the phone's orientation ?
On which articles is based the iVRy app to get the orientation of the phone ? 

Thanks,

PS: I didn't know how to contact you via github x)

**Comment by TheDeveloperGuy** [comment]
Yes, as the author of the software, I do know. Your tracker will receive this information via:

OnDevicePoseUpdated()

In future, please use the support forum, not the git issue tracker to ask questions. 

https://steamcommunity.com/app/992490/discussions/8/
