### ISSUE TITLE
About SteamVR with new HMD

### ISSUE THREAD

**Issue by DavidChen528** [TheDeveloperGuy/ivry_custom_tracking#2]
Hi，I want to start SteamVR direct on my HMD。
I use IVRDisplayComponent，and set Prop_EdidVendorID_Int32，Prop_EdidProductID_Int32，Prop_HasDriverDirectModeComponent_Bool = false
IsDisplayOnDesktop()
{
	return true;// also have try return false.
}
IsDisplayRealDisplay()
{
	return true;
}

but SteamVR always start fail：
Sun Feb 04 2024 11:01:55.443 [Info] - Found bad mirror window settings: 
Sun Feb 04 2024 11:01:55.499 [Info] - CGraphicsDevice Init...
Sun Feb 04 2024 11:01:55.499 [Info] - Headset display is on desktop
Sun Feb 04 2024 11:01:55.499 [Error] - Invalid adapter output specified! (-1) 887A0002
Sun Feb 04 2024 11:01:55.499 [Error] - Failed to init graphics device
Sun Feb 04 2024 11:01:55.508 [Info] - Failed to initialize compositor
Sun Feb 04 2024 11:01:55.508 [Info] - Failed to start compositor: VRInitError_Compositor_InvalidOutputDesktop

Also try to set those parameters can not help :
static const char * const k_pch_DirectMode_Section = "direct_mode";
static const char * const k_pch_DirectMode_Enable_Bool = "enable";
static const char * const k_pch_DirectMode_Count_Int32 = "count";
static const char * const k_pch_DirectMode_EdidVid_Int32 = "edidVid";
static const char * const k_pch_DirectMode_EdidPid_Int32 = "edidPid";

what can I do for it?

**Comment by DavidChen528** [comment]
@TheDeveloperGuy Could you help me？Thanks

**Comment by TheDeveloperGuy** [comment]
This is not an issue with the custom tracker for the iVRy SteamVR driver. It doesn't sound like an issue with the iVRy software at all, so not sure why you are raising issues on the repository. Please use email if you wish to inquire about consultancy services: ivry.vr@gmail.com
